In [3]:
import os
import csv
import string
import readability
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.colors
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from collections import defaultdict
from scipy import stats

In [4]:
Data_Root = '/kellogg/proj/hpk5609/Patent/Text/'

Test on subset

In [6]:
df_2001 = pd.read_csv(Data_Root+'Description_Text/pg_detail_desc_text_2001.tsv.zip', compression='zip', header=0, sep='\t', quotechar='"')

In [7]:
df_2001.head(3)

,pgpub_id,description_text,description_length
0,20010000001,31. The invention will be described in greater...,6584
1,20010000002,DETAILED DESCRIPTION OF THE INVENTION 65. The ...,29216
2,20010000003,DESCRIPTION OF THE PREFERRED EMBODIMENT 29. Th...,28479

In [17]:
len(df_2001)

56418

In [16]:
df_2001.loc[0]['description_text']

'31. The invention will be described in greater detail by way of specific examples. The following examples are offered for illustrative purposes, and are intended neither to limit or define the invention in any manner. \n EXAMPLE I 32. A solvent mixture in accordance with the invention was blended and added together to a standard vapor degreaser, the solvent mixture comprising: (I) about 90.0 wt. % n-propyl bromide; (ii) about 6 wt. % of a mixture of saturated terpenes, the terpene mixture comprising about 45 wt. % cis-pinane, about 45 wt. % trans-pinane, about 2 wt. % endo-isocamphene, about 2 wt. % &agr;-pinene, about 2 wt. % cis-para-menthane and about 2 wt. % trans-para-menthane; and (iii) about 4 wt. % of a mixture of low boiling solvents, the low boiling solvent mixture comprising about 0.5 wt. % nitromethane, about 0.5 wt. % 1,2-butylene oxide and about 3 wt. % 1,3-dioxolane. The thermostat on the vapor degreaser was adjusted to a temperature of about 160° F., and the system was allowed to equilibrate. After the mixture inside the solvent reservoir reached a temperature of about 160° F., the mixture began to boil. Upon inspection, a vapor layer several inches thick was observed inside the vapor degreaser unit. Enough vapor was being evolved to condense and be circulated from the chilled side of the vapor degreaser to the boiling side of the vapor degreaser. \n EXAMPLE II 33. Fifteen gallons of the solvent mixture described in Example I were added to a vapor phase degreaser. The thermostat on the vapor degreaser was adjusted to a temperature of about 160° F., and the system was allowed to equilibrate. After the mixture inside the solvent reservoir reached a temperature of about 160° F., the mixture began to boil. A basket of steel parts covered with lithium-based grease was placed in the vapor layer. After a period of about 30 seconds, the basket of steel parts was removed from the vapor layer. All of the lithium-based grease had been removed and the steel parts were completely clean. Using a similar procedure as that just described, pieces of sheet metal containing light mineral oils, silicone oils, lithium greases, and other types of industrial release fluids were placed in the vapor layer to be cleaned. After a period of about a minute, the pieces of sheet metal were removed from the vapor layer. All of the contaminants, i.e., the light mineral oils, silicone oils, lithium greases, and other types of industrial release fluids, had been removed. \n EXAMPLE III 34. Fifteen gallons of the solvent mixture described in Example I were added to a ultrasonic degreaser, which will operate effectively with the inventive solvent mixture at temperatures in the range of 70° F. to about 160° F. The ultrasonic degreaser had a transducer mounted at the base of the tank which operates in the range of 20 kHZ to 40 kHz. The thermostat on the ultrasonic degreaser was adjusted to a temperature of about 160° F., and the system was allowed to equilibrate. The ultrasonic degreaser also employed water chilled coils to control the solvent vapors and to eliminate the need for a local exhaust ventilation system. Several steel parts coated with lithium grease were immersed in the solvent for about one minute. The transducer alternately compressed and expanded the solvent thereby forming small bubbles which, in turn, cavitated at the surface of the lithium grease coated steel parts. The cavitation phenomenon disrupted the adhering soils and cleaned the parts. Using a similar procedure as that just described, pieces of sheet metal containing light mineral oils, silicone oils, lithium greases, and other types of industrial release fluids were immersed in the ultrasonic degreaser. After a period of about a minute, the pieces of sheet metal were removed from the vapor layer. All of the contaminants, i.e., the light mineral oils, silicone oils, lithium greases, and other types of industrial release fluids, had been removed. \n EXAMPLE IV 35. Five gallons of the solvent mixture described in Example I were added to an emulsion soak tank. A steel part coated with lithium grease was immersed for one minute into an emulsion soak tank containing the solvent mixture at room temperature. While some cleaning occurred, the resulting cleaning was not at the molecular level. Similarly, five gallons of the solvent mixture described in Example I were added to a heated power washer emulsion degreaser. The thermostat on this degreaser was adjusted to 156° F., just below the boiling point of n-propyl bromide, and the system was allowed to equilibrate. Thereafter, the solvent mixture was sprayed on steel parts which were coated with lithium grease. Upon inspection, it was observed that the resulting cleaning was at the molecular level. \n EXAMPLE V 36. Standard corrosion tests, similar to those performed by Dow Chemical Company, were performed using the solvent mixture of the invention, as oxidation is a potential problem with all solvent cleaners. In addition, methodology similar to that used by Dow Chemical Company was used to show equilivences to existing Clean Air Act banned solvents. In performing these test, strips of copper and steel measuring 1″ wide by 6″ long and of 20 mil thickness were buffed on a belt sander to remove any oxide films. Fifty milliliters of the solvent mixture described in Example I were placed in a cylindrical Pyrex glass container and strips were placed in so that 75% of the surface was immersed in the solvent. A sample container filled with tap water was used as a control for the test to insure that there were no alloys present in the metal strips which would have been prevented oxidation. The openings of the sample containers were all sealed with cork stoppers to reduce evaporation. After an eight hour incubation period and a 24 hour incubations period, the strips were removed and it was determined that the solvent mixture of the present invention was non-corrosive. 37. It is to be understood that the above description is intended to be illustrative and not restrictive. Many embodiments may be apparent to those of skill in the art upon reading the above description. The scope of the invention should, therefore, be determined not with reference to the foregoing description, but should instead be determined with reference to the appended claims, along with the full scope of equivalents to which such claims are entitled. The disclosures of all articles and references, including patent applications and publications, are incorporated herein by reference for all purposes.'

In [47]:
len(df_2001.loc[0]['description_text'].split())

1079

In [1]:
hype_dict = {
 'Importance': ['compelling',
 'critical',
 'crucial',
 'essential',
 'foundational',
 'fundamental',
 'imperative',
 'important',
 'indispensable',
 'invaluable',
 'key',
 'major',
 'paramount',
 'pivotal',
 'significant',
 'strategic',
 'timely',
 'ultimate',
 'urgent',
 'vital'],

'Novelty': ['creative',
 'emerging',
 'first',
 'groundbreaking',
 'innovative',
 'latest',
 'novel',
 'revolutionary',
 'unique',
 'unparalleled',
 'unprecedented'],
             
'Rigor': ['accurate',
 'advanced',
 'careful',
 'cohesive',
 'detailed',
 'nuanced',
 'powerful',
 'quality',
 'reproducible',
 'rigorous',
 'robust',
 'scientific',
 'sophisticated',
 'strong',
 'systematic'],
             
'Scale': ['ample',
 'biggest',
 'broad',
 'comprehensive',
 'considerable',
 'deeper',
 'diverse',
 'enormous',
 'expansive',
 'extensive',
 'fastest',
 'greatest',
 'huge',
 'immediate',
 'immense',
 'interdisciplinary',
 'international',
 'interprofessional',
 'largest',
 'massive',
 'multidisciplinary',
 'myriad',
 'overwhelming',
 'substantial',
 'top',
 'transdisciplinary',
 'tremendous',
 'vast'],
             
'Utility': ['accessible',
 'actionable',
 'deployable',
 'durable',
 'easy',
 'effective',
 'efficacious',
 'efficient',
 'generalizable',
 'ideal',
 'impactful',
 'intuitive',
 'meaningful',
 'productive',
 'ready',
 'relevant',
 'rich',
 'safer',
 'scalable',
 'seamless',
 'sustainable',
 'synergistic',
 'tailored',
 'tangible',
 'transformative',
 'user-friendly'],
             
'Quality': ['ambitious',
 'collegial',
 'dedicated',
 'exceptional',
 'experienced',
 'intellectual',
 'longstanding',
 'motivated',
 'premier',
 'prestigious',
 'promising',
 'qualified',
 'renowned',
 'senior',
 'skilled',
 'stellar',
 'successful',
 'talented',
 'vibrant'],
             
'Attitude': ['attractive',
 'confident',
 'exciting',
 'incredible',
 'interesting',
 'intriguing',
 'notable',
 'outstanding',
 'remarkable',
 'surprising'],
             
'Problem': ['alarming',
 'daunting',
 'desperate',
 'devastating',
 'dire',
 'dismal',
 'elusive',
 'stark',
 'unanswered',
 'unmet']
}

In [4]:
hype_words = set()
for cate in hype_dict:
    for w in hype_dict[cate]:
        hype_words.add(w)
hype_words_li = list(hype_words)

In [5]:
len(hype_words_li)

139

In [6]:
print(hype_words_li)

['pivotal', 'broad', 'outstanding', 'quality', 'transformative', 'productive', 'remarkable', 'foundational', 'fastest', 'accessible', 'sustainable', 'stellar', 'sophisticated', 'advanced', 'compelling', 'comprehensive', 'rigorous', 'ultimate', 'substantial', 'detailed', 'exceptional', 'unmet', 'synergistic', 'elusive', 'ample', 'durable', 'efficacious', 'essential', 'experienced', 'huge', 'cohesive', 'senior', 'important', 'interdisciplinary', 'easy', 'surprising', 'vibrant', 'interesting', 'innovative', 'extensive', 'seamless', 'overwhelming', 'scientific', 'nuanced', 'incredible', 'talented', 'tailored', 'daunting', 'impactful', 'imperative', 'novel', 'intuitive', 'scalable', 'deeper', 'unprecedented', 'strong', 'skilled', 'meaningful', 'unanswered', 'longstanding', 'groundbreaking', 'considerable', 'relevant', 'expansive', 'invaluable', 'crucial', 'enormous', 'intriguing', 'user-friendly', 'vast', 'collegial', 'multidisciplinary', 'biggest', 'qualified', 'confident', 'major', 'renowned', 'diverse', 'desperate', 'strategic', 'indispensable', 'attractive', 'international', 'paramount', 'immediate', 'careful', 'deployable', 'ideal', 'emerging', 'key', 'interprofessional', 'largest', 'transdisciplinary', 'tremendous', 'critical', 'fundamental', 'dismal', 'effective', 'ambitious', 'tangible', 'dedicated', 'notable', 'creative', 'systematic', 'promising', 'efficient', 'greatest', 'massive', 'motivated', 'safer', 'generalizable', 'accurate', 'immense', 'successful', 'exciting', 'devastating', 'dire', 'myriad', 'stark', 'rich', 'actionable', 'timely', 'robust', 'latest', 'powerful', 'ready', 'significant', 'premier', 'alarming', 'vital', 'urgent', 'top', 'prestigious', 'unique', 'unparalleled', 'intellectual', 'first', 'reproducible', 'revolutionary']

In [5]:
table = str.maketrans('', '', string.punctuation)

def parse_text(text):
    # don't use split(' ')
    words = text.lower().split()
    # rm punctuation
    words = [w.translate(table) for w in words]
    return words


def count_hype_words(text):
    words = parse_text(text)
    mdict = defaultdict(int)
    for w in words:
        if w in hype_words:
            mdict[w] += 1
    cn_li = [mdict[w] for w in hype_words_li]
    return cn_li
    
def cal_FleschReadingEase(text):
    valid_words = parse_text(text)
    if len(valid_words) < 3:
        return np.nan
        
    measures = readability.getmeasures(text, lang='en')
    return measures['readability grades']['FleschReadingEase']

In [ ]:
years = list(range(2001, 2024))

for year in years:
    df_2001 = pd.read_csv(Data_Root+'Description_Text/pg_detail_desc_text_%d.tsv.zip'%year, compression='zip', header=0, sep='\t', quotechar='"')
    df_2001 = df_2001.loc[~df_2001['description_text'].isna()]
    df_2001['flesch_reading_ease'] = df_2001['description_text'].apply(cal_FleschReadingEase)
    df_2001['hwords_cn_li'] = df_2001['description_text'].apply(count_hype_words)
    tem_df = pd.DataFrame(df_2001['hwords_cn_li'].values.tolist(), index = df_2001.index, columns=hype_words_li)
    df_2001 = pd.concat([df_2001, tem_df], axis=1)
    df_2001['total_num_hype_words'] = df_2001[hype_words_li].sum(axis=1)
    df_2001['num_words'] = df_2001['description_text'].str.split().str.len()
    df_2001['frac_hype_words'] = df_2001['total_num_hype_words'] / df_2001['num_words']
    df_2001.drop(columns=['description_text', 'hwords_cn_li']).to_csv(Data_Root+'pgpub_id_text_measure_%d.csv'%year, header=True, index=False, quoting=csv.QUOTE_MINIMAL)

Check description text

In [6]:
df = pd.read_csv('/kellogg/proj/hpk5609/Patent/patent_reg_data.csv', header=0, low_memory=False, \
                 dtype={'pgpub_id': str, 'application_id': str, 'patent_id': str})

In [7]:
len(df)

2748927

In [8]:
ids = set(df['pgpub_id'].astype(int))

In [10]:
len(ids)

2748927

In [11]:
years = list(range(2001, 2024))
df_li = []
for year in years:
    df_ = pd.read_csv(Data_Root+'Description_Text/pg_detail_desc_text_%d.tsv.zip'%year, compression='zip', header=0, sep='\t', quotechar='"')
    df_ = df_.loc[df_['pgpub_id'].isin(ids)]
    df_.index = range(len(df_))
    df_li.append(df_)

In [12]:
combined_df = pd.concat(df_li, axis=0)
# combined_df = combined_df.reset_index(drop=True)
combined_df.index = range(len(combined_df))

In [13]:
len(combined_df)

2748927

In [14]:
del df_li

In [15]:
combined_df.head()

,pgpub_id,description_text,description_length
0,20130086733,DESCRIPTION OF EMBODIMENTS\n\nThe present appl...,34678
1,20130086756,BEST MODE FOR CARRYING OUT THE INVENTION\n\nTh...,28092
2,20130086760,DETAILED DESCRIPTION\n\nReference will now be ...,21317
3,20130086767,DETAILED DESCRIPTION\n\nFIG. 1shows a wiper bl...,11114
4,20130086781,DETAILED DESCRIPTION OF THE PREFERRED EMBODIME...,38508

In [16]:
combined_df.to_csv(Data_Root+'pgpub_id_fulltext.csv', header=True, index=False, quoting=csv.QUOTE_ALL)

In [14]:
pd.set_option('display.max_colwidth', None)

In [48]:
print(combined_df.loc[combined_df['pgpub_id'] == 20220222861, 'description_text'])

6940692    DETAILED DESCRIPTION OF THE EMBODIMENTS\n\nThe technical solutions in the embodiments of the present disclosure will be described below in conjunction with the drawings in the embodiments of the present disclosure. Obviously, the described embodiments are some of the embodiments of the present disclosure, but not all of the embodiments. Based on the embodiments in this disclosure, all other embodiments obtained by those of ordinary skill in the art without creative work shall fall within the scope of this disclosure.\n\nUnless otherwise specified, all technical and scientific terms used in the embodiments of the present disclosure have the same meaning as commonly understood by those skilled in the technical field of the present disclosure. The terms used in this disclosure are only for the purpose of describing specific embodiments and are not intended to limit the scope of the present disclosure.\n\nThe data encoding method provided by various embodiments of the present disclosure may be applied to a data encoding device, and the data encoding device may be set on an intelligent terminal (such as a mobile phone, a tablet computer, etc.). In some embodiments, the embodiments of the present disclosure may be applied to an aircraft (such as an unmanned aerial vehicle). In other embodiments, the embodiments of the present disclosure may also be applied to other movable platforms (such as unmanned ships, unmanned vehicles, robots, etc.). The present disclosure has no limit on this.\n\nThe present disclosure provides a data encoding method to improve zero run length encoding of attribute transformation coefficients or attribute residual in point cloud encoding. A more comprehensive and effective construction method is provided for a context model used in arithmetic encoding of some syntax elements, which may improve the performance of attribute encoding in point cloud data without changing any coding complexity. Before the embodiments of the present disclosure are introduced, the context model in zero run length encoding and arithmetic encoding will be described first.\n\nIn one example, point cloud data is divided into two parts, geometry and attributes, for encoding respectively. When attributes are being encoded, attribute values are converted into transform coefficients or attribute residual through transformation or prediction, and then quantization and entropy encoding are performed on the transform coefficients or attribute residual. After transformation/prediction, a probability distribution of the original attribute information is changed. When the prediction method is reasonable and the prediction is relatively accurate, the obtained attribute residual distribution will be around 0 (ideally all residuals are 0). Therefore, a zero run length encoding method is mainly used for attribute encoding. This encoding method will perform statistics on whether the attribute residual or transform coefficient string sent to the encoder is 0. A zero run syntax element is used to record the number of consecutive occurrences of 0 for continuous 0 and residual encoding is not performed on these 0s. For non-zero values, zero run is naturally not equal to 0, and residual encoding needs to be performed on these non-zero values. For the non-zero attribute residual, instead of directly performing entropy encoding, the following operations are performed: subtracting 1 from the attribute residual; determining whether it is 0 after subtracting 1; when it is zero, setting a second flag bit “isZero” to 1, and ending the encoding of this value; when it is not 0 after subtracting 1, setting the second flag bit “isZero” to 0, and determining whether the attribute residual is 1; when it is 1, setting a first flag bit “isOne” to 1, and ending the encoding of the attribute residual; otherwise setting the first flag bit “isOne” to 0, and encoding the value obtained by subtracting 2 from the attribute residual (if this step is reached, that means the attribute residual is certainly not equal to 0 or 1 or 2, and hence2can be subtracted therefrom).\n\nFIG. 1is a flow chart of a zero run length encoding method in one example. As shown inFIG. 1, assuming that the attribute residual of one channel of the current point cloud point in the point cloud data to be encoded are: 73, 50, 32, 15, 0, 12, 0, 0, 0, . . . , 0, since all the initial values are not zero, all values of zero run are 0. When there are N consecutive zeros, the value of zero run is N. As shown inFIG. 1, the attribute residuals of a channel of the current point cloud point in the point cloud data to be encoded, which are 73, 50, 32, 15, 0, 12, 0, 0, 0, . . . , 0, are encoded to obtain code values after adding zero runs of: 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, N. Then the encoded values, 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, N, are binarized to obtain a binary code for indicating the first flag bit and/or the second flag bit. In some examples, the first flag bit may be “isOne,” and the second flag bit may be “isZero.”\n\nIn one example, when the encoded values, 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, N, are binarized, zero run is binarized using truncated unary code and then sent to an arithmetic encoder for encoding. For the two 1-bit flags of “isZero” and “isOne,” corresponding context models are constructed, and then arithmetic encoding is performed according to the context models. Since the attribute residuals generally have three channels (such as RGB, YUV, etc.), the attribute residuals of an encoded channel may be used to construct the context.\n\nIn one example, the attribute residuals of the three channels are respectively denoted as C1, C2, and C3. When encoding “isZero” and “isOne” of C1, there is no context model to refer to. When encoding “isZero” and “isOne” of C2, whether the value of C1 is zero is used as a reference and two different context models are constructed according to whether the value of C1 is zero. In the same way, when encoding “isZero” and “isOne” of C3, whether values of C1 and C2 are zero is used as a reference, and correspondingly there are four context models. Therefore, “isZero” and “isOne” each have seven context models for selection, as shown in Table 1, which is a table constructed by an existing context model.\n\nIn some embodiments, the three channels of the attribute residual may include RGB, where R is a red channel, G is a green channel, and B is a blue channel. In some examples, the three channels of the attribute residual may include YUV, where Y is a luminance channel, and U and V are chrominance channels.\n\nIn arithmetic encoding, the symbol information of the encoded syntax elements is also called context. The accurate use of context information is obviously beneficial to improve the efficiency of attribute encoding. The statistical information (mainly probability distribution) of appropriate context information is the context model.\n\nTABLE 1isZeroisOneC10//C21C1 == 0C1 == 02C1 != 0C1 != 0C33C1 == 0, C2 == 0C1 == 0, C2 == 04C1 == 0, C2 != 0C1 == 0, C2 != 05C1 != 0, C2 == 0C1 != 0, C2 == 06C1 != 0, C2 != 0C1 != 0, C2 != 0\n\nIn the existing technologies, the context model selection method of “isOne” and “isZero” have the same conditions, that is, whether the value of the encoded channels is 0. Statistic correlation between whether the encoded value is 0 and whether the value is 1 is not so strong. Therefore, the existing “isOne” context model is not optimized, and the “isOne” context model selection is unreasonable.\n\nThe present disclosure provides a method, a device, and a storage medium for data encoding/decoding, to alleviate above problems at least partially. In the present disclosure, a new context model construction method may be established for the flag bit of “isOne” and the context model construction method of “isZero” may remain unchanged. The context models of each of the two flag bits may be still maintained at7. Therefore, the total average code length of the arithmetic encoding of the “isOne” flag bit may be shortened without increasing additional complexity, and the performance and efficiency of point cloud data attribute encoding may be improved.\n\nThe present disclosure provides a data encoding method.FIG. 2is a flow chart of a data encoding method provided by one embodiment of the present disclosure. The method may be applied to a data encoding device as described above. As shown inFIG. 2, the method includes S201to S203.\n\nAt S201, attribute residual of a current point cloud point is obtained.\n\nIn one embodiment, the data encoding device may obtain the attribute residual of the current point cloud point.\n\nIn some embodiments, the attribute residual of the current point cloud point may include attribute residual of a first channel, attribute residual of a second channel, or attribute residual of a third channel.\n\nIn some embodiments, the first channel may include an R channel or a Y channel, the second channel may include a G channel or a U channel, and the third channel may include a B channel or a V channel.\n\nIn some embodiments, the first channel may include an R channel or a Y channel, the second channel may include a B channel or a V channel, and the third channel may include a G channel or a U channel.\n\nIn some embodiments, the attribute residual of the current point cloud point may be values greater than or equal to zero.\n\nAt S202, the attribute residual is binarized to obtain a binary code of the current point cloud point. The binary code of the current point cloud point may include a binary code for indicating a first flag bit and a binary code for indicating a second flag bit.\n\nIn one embodiment, the data encoding device may binarize the attribute residual to obtain the binary code of the current point cloud point. The binary code of the current point cloud point may include the binary code for indicating the first flag bit and the binary code for indicating the second flag bit.\n\nIn some embodiments, the binary code of the current point cloud point may include the binary code of the attribute residual of the first channel, the binary code of the attribute residual of the second channel, or the binary code of the attribute residual of the third channel. In some embodiments, the first channel, the second channel, and the third channel may be different channels.\n\nIn some embodiments, the first flag bit may be used to indicate whether the attribute residual of one channel of the current point cloud point is N+1, and the second flag bit may be used to indicate whether the attribute residual of one channel of the current point cloud point is N, where N is greater than or equal to 0.\n\nIn an example, the first flag bit may be used to indicate whether the attribute residual of one channel of the current point cloud point is 2, and the second flag bit may be used to indicate whether the attribute residual of one channel of the current point cloud point is 1.\n\nIn some embodiments, when the attribute residual of the first channel, the second channel, and the third channel is the same and is not equal to 0, the second flag bit in the binary code of the attribute residual of the first channel may be used to indicate whether the attribute residual of the first channel is 1; or, the first flag bit of the binary code of the attribute residual of the first channel may be used to indicate whether the attribute residual of the first channel is 2.\n\nIn some embodiments, when the attribute residual of the first channel, the second channel, and the third channel is not completely the same, the second flag bit of the binary code of the attribute residual of the first channel may be used to indicate whether the attribute residual of the first channel is 0; or, the first flag bit of the binary code of the attribute residual of the first channel is used to indicate whether the attribute residual of the first channel is 1.\n\nIn some embodiments, when the attribute residual of the first channel is less than or equal to 1, the second flag bit of the binary code used to indicate the attribute residual of the first channel may be included. When the attribute residual of the first channel is greater than or equal to 2, the second flag bit and the first flag bit of the binary code used to indicate the attribute residual of the first channel may be included.\n\nIn one embodiment, when the data encoding device binarizes the attribute residual to obtain the binary code of the current point cloud point, it may encode the attribute residual of the current point cloud point according to a preset encoding method, to obtain encoded values, and then and the encoded values may be binarized to obtain the binary code of the current point cloud point.\n\nIn one embodiment, when the data encoding device encode the attribute residual of the current point cloud point according to the preset encoding method to obtain the encoded values, the zero run length encoding method may be used. For repeated and consecutive occurrences of 0s in the attribute residual of a channel of the current point cloud point, a zero run syntax element may be used to record the number of consecutive occurrences of 0s, and the residual encoding may be no longer performed on these 0s. For non-zero values of the attribute residual in a channel, zero run may be naturally equal to 0, and these non-zero values may need to be encoded to obtain the encoded values of the attribute residual of the channel.\n\nIn one example shown inFIG. 1, assuming that the attribute residuals of the first channel of the current point cloud point are 73, 50, 32, 15, 0, 12, 0, 0, 0, . . . , 0, the attribute residuals of the first channel include N consecutive zeros, and the zero run length encoding method may be used to encode the attribute residuals of the first channel, 73, 50, 32, 15, 0, 12, 0, 0, 0, . . . , 0, and the obtained encoded values are: 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, N.\n\nIn one embodiment, when the data encoding device binarizes the encoded values to obtain the binary code of the current point cloud point, it may not directly perform entropy encoding on the encoded values of the non-zero attribute residual. Instead, it may perform the operations including: subtracting 1 from an attribute residual; determining whether the attribute residual is 0 after subtracting 1; when the attribute residual is 0 after subtracting 1, setting the second flag bit “isZero” to 1, and ending the encoding of this value; when the attribute residual is not 0 after subtracting 1, setting the second flag bit “isZero” to 0, and determining whether the attribute residual is 1 after subtracting 1; when the attribute residual is 1 after subtracting 1, setting the first flag bit “isOne” to 1, and ending the encoding of the value; when the attribute residual is not 1 after subtracting 1, setting the first flag bit “isOne” to 0, and performing arithmetic encoding on the value after subtracting 2 from the value.\n\nIn one example shown inFIG. 1, the attribute residual of the first channel of the current point cloud point is 73, 50, 32, 15, 0, 12, 0, 0, 0, . . . , 0, and the obtained encoded values are: 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, N. The data encoding device may binarize the encoded values 0, 73, 0, 50, 0, 32, 0, 15, 1, 12, and N. In the process of binarization, the values of 73, 50, 32, and 15 after subtracting 1 are all not 1, the first flag bit “isOne” corresponding to 73, 50, 32, and 15 respectively may be set to 0. Since 1 in the encoded values is 0 after subtracting 1, the second flag bit “isZero” corresponding to 1 may be set to 1. The remaining encoding values of 0 may be not encoded. Therefore, the binary code of the attribute residual of the first channel of the current point cloud point composed of 0 and 1 may be obtained.\n\nThrough this implementation, the attribute residual of the current point cloud point may be binarized, and the binary code including the first flag bit and the second flag bit may be obtained. The process of binarization may be simplified to reduce the complexity of the binarization, which may be beneficial to selecting the corresponding context model according to different flag bits during subsequent encoding to encode the binary code corresponding to different flag bits. The encoding efficiency may be improved.\n\nAt S203, a first context model for encoding the binary code of the first flag bit is selected from a context model list according to a first condition.\n\nIn one embodiment, the data encoding device may select the first context model for encoding the binary code of the first flag bit from the context model list according to the first condition.\n\nIn one embodiment, when the data encoding device selects the first context model for encoding the binary code of the first flag bit from the context model list according to the first condition, it may select the first context model for encoding the binary code of the first flag bit of the attribute residual of the second channel from the context model list according to whether the attribute residual of the first channel of the current point cloud point is larger than a first preset threshold. The first preset threshold may be larger than 0. In some other embodiments, the first preset threshold may be larger than or equal to 1. In some embodiment, each of the first flag bit and the second bit of the attribute residual of the first channel may have one context model. In some embodiments, each of the first flag bit and the second bit of the attribute residual of the second channel may have two context models.\n\nIn one embodiment, when the attribute residual of the first channel of the current point cloud point is larger than the first preset threshold, the selected first context model for encoding the binary code of the first flag bit of the attribute residual of the second channel may be a context model in the context model list corresponding to a first index. When the attribute residual of the first channel of the current point cloud point is not larger than the first preset threshold, the selected first context model for encoding the binary code of the first flag bit of the attribute residual of the second channel may be a context model in the context model list corresponding to a second index.\n\nIn one example shown in Table 2, which is a table for constructing the context model provided by one embodiment of the present disclosure, the first preset threshold is larger than or equal to 1, the attribute residual of the first channel is C1, the attribute residual of the second channel is C2. When the attribute residual C1 of the first channel of the current point cloud point is larger than 1, the selected first context model for encoding the binary code of the first flag bit “isOne” of the attribute residual C2 of the second channel is the first context model corresponding o the first index (that is, the index 2) in the context model list. When the attribute residual C1 of the first channel of the current point cloud point is less than or equal to 1, the selected first context model for encoding the binary code of the first flag bit “isOne” of the attribute residual C2 of the second channel is the first context model corresponding o the second index (that is, the index 1) in the context model list.\n\nTABLE 2isZeroisOneC10//C21C1 == 0C1 <= 12C1 != 0C1 > 1C33C1 == 0, C2 == 0C1 <= 1, C2 <= 14C1 == 0, C2 != 0C1 <= 1, C2 > 15C1 != 0, C2 == 0C1 > 1, C2 <= 16C1 != 0, C2 != 0C1 > 1, C2 > 1\n\nIn one embodiment, when the attribute residual of the first channel of the current point cloud point is not equal to the first preset threshold, the selected first context model for encoding the binary code of the first flag bit of the attribute residual of the second channel may be a context model in the context model list corresponding to a first index. When the attribute residual of the first channel of the current po

In [49]:
print(combined_df.loc[combined_df['pgpub_id'] == 20210227560, 'description_text'])

6535095    DETAILED DESCRIPTION OF ILLUSTRATIVE EMBODIMENTS\n\nTo improve rate experience of a cell edge user for NR, as shown inFIG. 1, a scenario in which a plurality of transmit/receive points (Tx/Rx point, TRP) are used as network devices is introduced. The transmit/receive point may be an antenna, a radio frequency unit, a femto base station, a pico base station, a micro base station, an urban base station, or the like. This is not specifically limited herein. In a typical scenario, a first TRP110sends first DCI to a terminal device120through a first physical downlink control channel (PDCCH), where the first DCI is used to indicate the terminal device to receive a first transport block on a first time-frequency resource; and a second TRP130sends second downlink control information DCI to the terminal device120through a second PDCCH, where the second DCI is used to indicate the terminal device to receive a second transport block on a second time-frequency resource. The first time-frequency resource and the second time-frequency resource may overlap, or may not overlap.\n\nAs shown inFIG. 2, a first transport block and a second transport block are always mapped to a first CW, in other words, the first transport block and the second transport block are always mapped to a same CW. Because the terminal device obtains only one decoding result after decoding one CW, after decoding the first CW and obtaining a first decoding result, the terminal device feeds back the first decoding result to the first TRP and/or the second TRP. Therefore, if the terminal device fails to decode the first transport block and successfully decodes the second transport block, the terminal device may feed back only a NACK due to a limitation of an existing condition. Therefore, the first TRP retransmits the first transport block, and the second TRP also retransmits the second transport block. It may be learned that a method for determining a correspondence between a transport block and a codeword shown inFIG. 2is improper.\n\nTo resolve the foregoing problem, this application proposes a method for determining a correspondence between a transport block and a codeword, a related device, and a system, so that the correspondence between a transport block and a codeword can be properly determined.\n\nThis application may be applied to a 5GNR system, or may be applied to another communications system, provided that one entity in the communications system needs to send transmission direction indication information, and another entity needs to receive the indication information and determine a transmission direction within a specific period of time according to the indication information.\n\nIn a specific embodiment, as shown inFIG. 3, a network device and a terminal device1to a terminal device6constitute a communications system. In the communications system, the terminal device1to the terminal device6may send uplink data to a base station, and the network device needs to receive the uplink data sent by the terminal device1to the terminal device6. In addition, the terminal device4to the terminal device6may also form a communications system. In the communications system, the network device may send downlink information to the terminal device1, the terminal device2, the terminal device, and the like. The terminal device5may also send downlink information to the terminal device4and the terminal device6.\n\nThe network device may be a network-side entity configured to transmit or receive a signal, such as a new generation NodeB (new generation Node B, gNodeB). The network device may be alternatively a device configured to communicate with a mobile device. The network device may be an access point (AP) in a wireless local area network (Wireless LAN, WLAN), a base transceiver station (BTS) in a global system for mobile communications (GSM) or code division multiple access (CDMA), or a NodeB (base station) in wideband code division multiple access (WCDMA); or may be an evolved NodeB (Evolutional Node B, eNB or eNodeB) in long term evolution (LTE), a relay station, an access point, a vehicle-mounted device, a wearable device, a network device in a future 5G network, a network device in a future evolved public land mobile network (PLMN), a gNodeB in an NR system, or the like. In addition, in the embodiments of the present invention, the network device provides a service for a cell, and the terminal device communicates with the network device by using a transmission resource (for example, a frequency domain resource or a spectrum resource) used by the cell. The cell may be a cell corresponding to the network device (for example, a base station). The cell may belong to a macro base station, or may belong to a base station corresponding to a small cell. The small cell herein may include a metro cell, a micro cell, a pico cell, a femto cell, and the like. These small cells are characterized by a small coverage area and low transmit power, and are applicable to providing a high-rate data transmission service.\n\nThe terminal device may be a user-side entity configured to receive or transmit a signal, such as new generation user equipment (new generation UE, gUE). The terminal device may also be referred to as a terminal device (User Equipment, UE), an access terminal, a subscriber unit, a subscriber station, a mobile station, a mobile console, a remote station, a remote terminal, a mobile device, a user terminal, a terminal, a wireless communication device, a user agent, a user apparatus, or the like. The terminal device may be a station (ST) in a wireless local area network (WLAN), and may be a cellular phone, a cordless phone, a session initiation protocol (SIP) phone, a wireless local loop (WLL) station, a personal digital assistant (PDA) device, a handheld device having a wireless communication function, a computing device, another processing device connected to a wireless modem, a vehicle-mounted device, a wearable device, a terminal device in a next-generation communications system such as a fifth-generation communications (fifth-generation, 5G) network, a terminal device in a future evolved public land mobile network (PLMN), or a terminal device in a new radio (NR) communications system. As an example instead of a limitation, in the embodiments of the present invention, the terminal device may be alternatively a wearable device. The wearable device may also be referred to as a wearable intelligent device, and is a general name of a wearable device that is developed after daily wear is intelligently designed by using a wearable technology, such as glasses, gloves, a watch, clothing, and shoes. The wearable device is a portable device that is directly worn on a body, or integrated into clothes or accessories of a user. The wearable device is not only a hardware device, but can also implement a powerful function by using software support, data interaction, and cloud interaction. A generalized wearable intelligent device includes smartwatches, smart glasses, or the like that have full functions and a large size and that may implement all or partial functions without depending on a smartphone, and focuses only on a specific type of application function and needs to be used together with another device such as a smartphone, for example, various types of smart bands and smart jewelry that perform physical sign monitoring.\n\nFIG. 4is a schematic flowchart of a method for determining a correspondence between a transport block and a codeword according to an embodiment of this application. As shown inFIG. 4, the method for determining a correspondence between a transport block and a codeword in this embodiment of this application includes the following steps.\n\nS101: A first network device generates first DCI, where the first DCI is used to indicate the terminal device to receive a first transport block on a first time-frequency resource. In a specific embodiment, the first DCI is carried on a first PDCCH channel, and the first transport block is carried on a first downlink channel. Optionally, the first downlink channel may be a first PDSCH.\n\nS102: The first network device sends the first DCI to the terminal device, and correspondingly, the terminal device receives the first DCI sent by the first network device.\n\nS103: A second network device generates second DCI, where the second DCI is used to indicate the terminal device to receive a second transport block on a second time-frequency resource.\n\nIn a specific embodiment, the second transport block is carried on a second downlink channel.\n\nS104: The second network device sends the second DCI to the terminal device, and correspondingly, the terminal device receives the second DCI sent by the second network device.\n\nIn a specific embodiment, the second DCI is carried on a second PDCCH channel, and the second transport block is carried on a second downlink channel. For example, the second downlink channel may be a second PDSCH.\n\nS105: The terminal device determines, based on first information, that the first transport block is mapped to a first codeword.\n\nFor example, the first information includes at least one of the following: a first search space set in which the first DCI is located, a first DCI format corresponding to the first DCI, a first radio network identifier RNTI used for scrambling the first DCI, and a first bit field included in the first DCI.\n\nFor example, the terminal device may determine, based on the first information, that the second transport block is mapped to a second codeword.\n\nS106: The terminal device determines, based on second information, that the second transport block is mapped to the second codeword, where the second information includes at least one of the following: a second search space set in which the second DCI is located, a second DCI format corresponding to the second DCI, a second radio network identifier RNTI used for scrambling the second DCI, and a second bit field included in the second DCI. Optionally, the terminal device determines, based on the second information, that the first transport block is mapped to the first codeword.\n\nIt may be understood that, in the foregoing example, that step S103and step S104are performed after step S101and step S102is used as an example for description. However, in actual application, step S103and step S104may be performed simultaneously with step S101and step S102, or step S103and step S104may be performed before step S101and step S102. This is not specifically limited herein.\n\nIn this embodiment of this application, the terminal device may have a conflict problem of being mapped to hybrid automatic repeat request (HARQ) information corresponding to a same codeword. The HARQ information includes an acknowledgment (ACK) and/or a negative acknowledgement (NACK). Specifically, the terminal device may determine, based on the first information, that the first transport block is mapped to the first codeword, and that the second transport block is mapped to the second codeword. In other words, different transport blocks scheduled by different DCI may be mapped to different codewords, so that the terminal device can separately feed back HARQ information corresponding to the first transport block and HARQ information corresponding to the second transport block. If the HARQ information corresponding to the first transport block is a NACK, a decoding result is a failure, and therefore, the first network device retransmits the first transport block. In addition, if the HARQ information corresponding to the second transport block is an ACK, a decoding result is a success, and therefore, the second network device does not need to retransmit the second transport block. Therefore, use efficiency of system resources is improved. Therefore, through determining of the correspondence between a transport block and a codeword, feedback accuracy of the HARQ information can be improved, and therefore, the use efficiency of system resources is improved.\n\nIn a specific embodiment of this application, the first network device may be the first TRP shown inFIG. 1, and the second network device may be the second TRP shown inFIG. 2. Therefore, the problem between the first TRP and the second TRP inFIG. 1also exists between the first network device and the second network device.\n\nIn a specific embodiment of this application, the first DCI is further used to indicate transmission information of the first downlink channel. For example, the transmission information of the first downlink channel includes at least one of the following: time-frequency resource information of the first downlink channel that carries the first transport block, modulation and coding scheme information of the first transport block, redundancy version information of the first transport block, reference signal information corresponding to the first transport block, and the like. It may be understood that the first DCI may be further used to carry transmission information of another first downlink channel. This is not specifically limited herein. There may be one or more first downlink channels herein. This is not specifically limited herein.\n\nIn a specific embodiment of this application, the second DCI is further used to indicate transmission information of the second downlink channel, for example, time-frequency resource information of the second downlink channel that carries the second transport block, modulation and coding scheme information of the second transport block, redundancy version information of the second transport block, and reference signal information corresponding to the second transport block. It may be understood that the second DCI may be further used to carry transmission information of another second downlink channel. This is not specifically limited herein. There may be one or more second downlink channels herein. This is not specifically limited herein.\n\nIn a specific embodiment of this application, the time-frequency resource information includes time domain information and/or frequency domain information. The frequency domain resource may be one or more resource blocks (RB), or may be one or more resource elements (RE), or may be one or more carriers/serving cells, or may be one or more bandwidth parts (BWP), or may be one or more RBs on one or more BWPs on one or more carriers, or may be one or more REs on one or more RBs on one or more BWPs on one or more carriers. The time domain resource may be one or more timeslots, or may be one or more symbols in one or more timeslots. The symbol may be an orthogonal frequency division multiplexing (OFDM) symbol. The OFDM symbol may use transform precoding, or may not use transform precoding. If transform precoding is used, the OFDM symbol may also be referred to as a single carrier-frequency division multiplexing (SC-FDM) symbol.\n\nIn a specific embodiment of this application, the modulation and coding scheme information includes a modulation scheme and a coding rate. The modulation scheme includes at least one of the following: binary phase shift keying (BPSK), quadrature phase shift keying (QPSK), 16 quadrature amplitude modulation (QAM), 64 QAM, and 256 QAM. The modulation scheme is generally represented by a modulation order. A modulation order 1 corresponds to pi/2 BPSK, a modulation order 2 corresponds to QPSK, a modulation order 4 corresponds to 16 QAM, a modulation order 6 corresponds to 64 QAM, and a modulation order 8 corresponds to 256 QAM. A value of the coding rate×1024 includes a value greater than or equal to 30 and less than or equal to 948.\n\nIn a specific embodiment of this application, the redundancy version information includes one of {0, 1, 2, 3}.\n\nIn a specific embodiment of this application, the reference signal information includes an antenna port number.\n\nIn a specific embodiment of this application, higher-layer signaling may be signaling sent by a higher-layer protocol layer, and the higher-layer protocol layer is at least one protocol layer in protocol layers above a physical layer. The higher-layer protocol layer may be specifically at least one of the following protocol layers: a medium access control (MAC) layer, a radio link control (RLC) layer, a packet data convergence protocol (PDCP) layer, a radio resource control (RRC) layer, and a non-access stratum (NAS).\n\nIn a specific embodiment of this application, a manner in which the terminal device determines, based on the first information, that the first transport block is mapped to the first codeword, and/or a manner in which the terminal device determines, based on the second information, that the second transport block is mapped to the second codeword include/includes at least the following several manners:\n\nIn a first manner, the terminal device determines, based on the first bit field included in the first DCI, that the first transport block is mapped to the first codeword, and/or the terminal device determines, based on the second bit field included in the second DCI, that the second transport block is mapped to the second codeword. The first bit field included in the first DCI is at least one of the following: a first modulation and coding scheme MCS bit field, a first redundancy version RV bit field, a first count downlink assignment index C-DAI, a first total downlink assignment index T-DAI, and an indication field of a correspondence between the first transport block and the codeword. The second bit field included in the second DCI is at least one of the following: a second MCS bit field, a second RV bit field, a second C-DAI, a second T-DAI, and an indication field of a correspondence between the second transport block and the codeword.\n\nIn a specific embodiment, as shown inFIG. 5, DCI may include one or more bit fields. For example, when a maximum quantity of codewords supported by the terminal device is configured as 2, a plurality of bit fields may include a DCI format bit field of 1 bit, a frequency domain resource bit field of a plurality of bits, a first MCS bit field of 5 bits, a first RV bit field of 2 bits, a second MCS bit field of 5 bits, a second RV bit field of 2 bits, a DAI bit field of 4 bits (including a C-DAI and a T-DAI), a HARQ-ID bit field of 3 to 4 bits, a TPC command for PUCCH bit field of 2 bits, and the like. It should be understood that the foregoing bit field is merely an example, and should not constitute a specific limitation. It should be specially noted that in this embodiment of the present invention, the plurality of bit fields may include two or more bit fields.\n\nSpecifically, a specific implementation of the first manner includes at least the following several manners, and the several manners are separately described in detail below.\n\n(1) The terminal device determines, based on the first MCS bit field and/or the first RV bit field included in the first DCI, that the first transport block is mapped to the first codeword, and/or the terminal device determines, based on the second MCS bit field and/or the second RV included in the second DCI, that the second transport block is mapped to the second codeword. Specifically:\n\nOptionally, a maximum quantity, configured in any serving cell by using higher layer signaling, of codewords supported by the terminal device is 2.\n\nIt should be noted that a value of the bit field and/or the RV bit field in the foregoing solution may be a specific value, or may be a non-specific value. The specific value may be configured by using the higher layer signaling, or may be pre-defined. It may be understood that a value of the first MCS bit field is used to indicate a first MCS index, a value of the first RV bit field is used to indicate a first RV, a value of the second MCS bit field is used to indicate a second MCS index, and a value of the second RV bit field is used to indicate a second RV. For example, the specific value 

In [41]:
# 6130175 words (max length)
tem = combined_df.loc[combined_df['pgpub_id'] == 20140259212, 'description_text'].values[0]

In [47]:
tem[:5000]

'In a further embodiment, the present invention relates in paragraphs [0000.1.1.2] to [0514.1.1.2] to a further process for the production of at least a, preferably a, fine chemical selected from the group consisting of arginine, glutamate, glutamine and proline, as defined below and corresponding embodiments as described herein as follows\n\n[0001.1.1.2] to [0011.1.1.2] for the disclosure of these paragraphs see [0001.1.1.1] to [0011.1.1.1] above.\n\nIt is an object of the present invention to develop an inexpensive process for the synthesis of arginine, glutamate, glutamine and/or proline.\n\nfor the disclosure of this paragraph see [0013.1.1.1] above.\n\nAccordingly, in a first embodiment, the invention relates to a process for the production of at least one, preferably a, fine chemical selected from the group consisting of:\n\narginine, glutamate, glutamine and proline, or, in other words, of the “fine chemical” or “fine chemical of the invention”.\n\nThe terms “fine chemical of the invention”, “fine chemical” or “the fine chemical” are used herein equally and relate in context of the paragraphs or sections [0014.1.2.2] to [0514.1.1.2] essentially to the metabolite or the metabolites indicated in column 7, application no. 2 of Tables I, II and IV in the respective line.\n\nFurther, the term “in context of any of the paragraphs [0014.1.2.2] to [0514.1.1.2]” as used herein means that for any of said paragraphs [0014.1.2.2] to [0514.1.1.2] the term “the fine chemical” is understood to follow the definition of paragraphs or sections [0014.1.2.2] and [0015.1.2.2], independently whether it refers to any other paragraph or not and whether the reference recites the term “fine chemical” in an other context.\n\nThus, in cases where one or more paragraphs or sections are incorporated by reference into any of the present paragraphs [0014.1.2.2] to [0514.1.1.2], e.g. by usage of the term “see paragraph” or the term “for the disclosure of this paragraph see the disclosure of paragraph” or the term “incorporated by reference” or a corresponding term, the incorporated paragraph, section or term “the fine chemical” is also understood to have the meaning according to the definition of paragraph [0014.1.2.2] and [0015.1.2.2].\n\nAccordingly, in one embodiment, the term “fine chemical of the invention”, “fine chemical” or “the fine chemical” as used herein (alone or in combination, like in FCRP) means “arginine in context of the nucleic acid or polypeptide sequences listed in the respective same line of any one of Tables I to IV of application no. 2 and indicating in column 7 the metabolite “arginine”. In one embodiment, the term arginine or the term “fine chemical” mean in context of the paragraphs or sections [0014.1.2.2] to [0514.1.1.2] at least one chemical compound with an activity of the above mentioned arginine, respectively.\n\nAccordingly, in one embodiment, the term “fine chemical of the invention”, “fine chemical” or “the fine chemical” as used herein (alone or in combination, like in FCRP) means “glutamate in context of the nucleic acid or polypeptide sequences listed in the respective same line of any one of Tables I to IV of application no. 2 and indicating in column 7 the metabolite “glutamate”. In one embodiment, the term glutamate or the term “fine chemical” mean in context of the paragraphs or sections [0014.1.2.2] to [0514.1.1.2] at least one chemical compound with an activity of the above mentioned glutamate, respectively.\n\nAccordingly, in one embodiment, the term “fine chemical of the invention”, “fine chemical” or “the fine chemical” as used herein (alone or in combination, like in FCRP) means “glutamine in context of the nucleic acid or polypeptide sequences listed in the respective same line of any one of Tables I to IV of application no. 2 and indicating in column 7 the metabolite “glutamine”. In one embodiment, the term glutamine or the term “fine chemical” mean in context of the paragraphs or sections [0014.1.2.2] to [0514.1.1.2] at least one chemical compound with an activity of the above mentioned glutamine, respectively.\n\nAccordingly, in one embodiment, the term “fine chemical of the invention”, “fine chemical” or “the fine chemical” as used herein (alone or in combination, like in FCRP) means “proline in context of the nucleic acid or polypeptide sequences listed in the respective same line of any one of Tables I to IV of application no. 2 and indicating in column 7 the metabolite “proline”. In one embodiment, the term proline or the term “fine chemical” mean in context of the paragraphs or sections [0014.1.2.2] to [0514.1.1.2] at least one chemical compound with an activity of the above mentioned proline, respectively.\n\nAccordingly, in one embodiment, the terms “fine chemical of the invention”, “fine chemical” or “the fine chemical” mean in context of any of the paragraphs [0014.1.2.2] to [0514.1.1.2] arginine, preferably the L-enantiomer of arginine, its salts, ester or amides in free form or bound to proteins.'

### Count We words

In [8]:
we_words = set(['we', 'us', 'our', 'ours'])

In [10]:
def count_total_we_words(text):
    words = parse_text(text)
    tot = 0
    for w in words:
        if w in we_words:
            tot += 1
    return tot

In [11]:
years = list(range(2001, 2024))

for year in years:
    df_2001 = pd.read_csv(Data_Root+'Description_Text/pg_detail_desc_text_%d.tsv.zip'%year, compression='zip', header=0, sep='\t', quotechar='"')
    df_2001 = df_2001.loc[~df_2001['description_text'].isna()]
    df_2001['total_num_we_words'] = df_2001['description_text'].apply(count_total_we_words)
    df_2001['num_words'] = df_2001['description_text'].str.split().str.len()
    df_2001['frac_we_words'] = df_2001['total_num_we_words'] / df_2001['num_words']
    df_2001.drop(columns=['description_text']).to_csv(Data_Root+'pgpub_id_we_measure_%d.csv'%year, header=True, index=False, quoting=csv.QUOTE_MINIMAL)